### PR TITLE
Feat: Implement CustomUser model

### PR DESCRIPTION
**Pull request by hslim8888**
---

<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>

> #### What Changed
> Added
> - user
> - AUTH_USER_MODEL
> - CustomUser
> - CustomUserManager
> - create_user
> - create_superuser
> #### Testing
> Test the signup functionality by creating a new user and verifying that the user is saved correctly in the database.
> #### Reasoning
> This change adds a custom user model and manager to the project, allowing for more flexibility and customization in user authentication and management.
</details>

### CODE REVIEW

**Review by kyu1204 — APPROVED** [review]
LGTM

**Comment by kyu1204** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1** <a href="https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/1" target="_blank">Graphite</a>  👈
    * **PR #2** <a href="https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/2" target="_blank">Graphite</a> 
      * **PR #3** <a href="https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/3" target="_blank">Graphite</a> 
        * **PR #4** <a href="https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/4" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/1?utm_source=stack-comment).

**Comment by hslim8888** [comment]
### Merge Activity

* **Oct 9, 12:40 AM**: @hslim8888 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/1).
* **Oct 9, 12:40 AM**: @hslim8888 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/mango-signup/1).

**Comment by yourHooni** [comment]
LGTM

**Pull request merged**
